name: Install Release To Sandbox

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Target Org'  
        options: 
        - SIT
        - UAT
        required: true
        default: SIT

jobs:
  InstallPackages:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/vlocity_sfdx:core-sf-cli
    steps:  
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set Up Variables
      id: setup_variables
      env:
          ORG_NAME: ${{ inputs.environment }}
      run: |
        CLIENT_ID="${ORG_NAME}_CLIENTID"
        USERNAME="${ORG_NAME}_SANDBOX_USERNAME"
        echo "CLIENT_ID=${CLIENT_ID}\n" >> $GITHUB_OUTPUT
        echo "USERNAME=${USERNAME}\n" >> $GITHUB_OUTPUT
        echo "GITHUB_OUTPUT:"
        cat "$GITHUB_OUTPUT"
    - name: Login To Orgs
      run: |
        echo "${{ secrets.RSA_PRIVATE_KEY }}"   > server.key
        echo "### Login DevHub"
        sf auth jwt grant --client-id ${{ secrets.DEVHUB_clientid }}  --jwt-key-file server.key --username ${{ secrets.DEVHUB_USERNAME }} --instance-url https://login.salesforce.com --alias DEVHUB
        echo "### Login To Org"
        sf auth jwt grant --client-id ${{ secrets[steps.setup_variables.outputs.CLIENT_ID] }}  --jwt-key-file server.key --username ${{ secrets[steps.setup_variables.outputs.USERNAME] }} --instance-url https://test.salesforce.com --alias SANDBOX_ALIAS
        sf org list
    - name: Core - Install Salesforce Package
      run: |
        sf org list
        ./scripts/bash/Get_Latest_Version_Package.sh DEVHUB core
        PACKAGE_ID=$(cat core_PID.txt)
        echo "PACKAGE_ID:${PACKAGE_ID}"
        sf package install --package ${PACKAGE_ID} --target-org SANDBOX_ALIAS --wait 1000 --publish-wait 1000 --security-type AdminsOnly --installation-key ${{ secrets.PACKAGES_KEY }}
    - name: App1 - Install Salesforce Package
      run: |
        sf org list
        ./scripts/bash/Get_Latest_Version_Package.sh DEVHUB App1
        PACKAGE_ID=$(cat App1_PID.txt)
        echo "PACKAGE_ID:${PACKAGE_ID}"
        sf package install --package ${PACKAGE_ID} --target-org SANDBOX_ALIAS --wait 1000 --publish-wait 1000 --security-type AdminsOnly --installation-key ${{ secrets.PACKAGES_KEY }}
    - name: App2 - Install Salesforce Package
      run: |
        sf org list
        ./scripts/bash/Get_Latest_Version_Package.sh DEVHUB App2
        PACKAGE_ID=$(cat App2_PID.txt)
        echo "PACKAGE_ID:${PACKAGE_ID}"
        sf package install --package ${PACKAGE_ID} --target-org SANDBOX_ALIAS --wait 1000 --publish-wait 1000 --security-type AdminsOnly --installation-key ${{ secrets.PACKAGES_KEY }}

